version: '3'

services:
  lgpd-pro:
    build: .
    image: marcosspeca/lgpd-pro
    container_name: lgpd-pro
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    volumes:
      - ./app:/lgpdpro/app
