version: '3'

services:
  lgpd-pro:
    build: .
    container_name: ldpg-pro
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/lgpdpro/app
